name: check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Run [lint, format]
        run: |
          pnpm install --frozen-lockfile
          pnpm run lint
          pnpm run format --check --no-write
